# Inspired by https://github.com/keycloak/keycloak/blob/main/.github/ISSUE_TEMPLATE/bug.yml
---
name: Bug Report
description: Report a non-security sensitive bug in todos service
labels:
  - "kind/bug"
  - "status/new"
body:
  - type: checkboxes
    attributes:
      label: Before reporting an issue
      description: |
        Please search to see if the issue is already reported, and try to reproduce the issue on the latest release.

        Any reported issues must be reproducible in the [latest](https://github.com/avisiedo/go-microservice-1/releases/latest) version of todos.

        **⚠️ Failing to follow these guidelines may result in your issue being closed without action. ⚠️**
      options:
        - label: I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.
          required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Affected area
      options:
        - ""
        - api-http
        - api-event
        - presenter-http-echo
        - presenter-event
        - interactor
        - repository-db
        - repository-client
        - repository-s3
        - client
        - metrics
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        ### Summary
        ### Steps to replay
        ### Current behavior
        ### Expected behavior
        ### Additional information
      placeholder: Bug Description
