# Inspired by 
---
name: Bug Report
description: Report a non-security sensitive bug in idmsvc-backend
labels: ["kind/bug","status/new"]
body:
  - type: checkboxes
    attributes:
      label: Before reporting an issue
      description: |
        Please search to see if the issue is already reported, and try to reproduce the issue on the latest release.

        Any reported issues must be reproducible in the [latest](https://github.com/podengo-project/idmsvc-backend/releases/latest) version of idmsvc-backend.

        **⚠️ Failing to follow these guidelines may result in your issue being closed without action. ⚠️**
      options:
        - label: I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.
          required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Affected area
      options:
        - ""
        - api
        - handler
        - repository
        - interactor
        - presenter
        - client
        - metrics
        - rbac
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: 
      placeholder: 