// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockApplicationService creates a new instance of MockApplicationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApplicationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApplicationService {
	mock := &MockApplicationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockApplicationService is an autogenerated mock type for the ApplicationService type
type MockApplicationService struct {
	mock.Mock
}

type MockApplicationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApplicationService) EXPECT() *MockApplicationService_Expecter {
	return &MockApplicationService_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockApplicationService
func (_mock *MockApplicationService) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplicationService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockApplicationService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockApplicationService_Expecter) Start() *MockApplicationService_Start_Call {
	return &MockApplicationService_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockApplicationService_Start_Call) Run(run func()) *MockApplicationService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockApplicationService_Start_Call) Return(err error) *MockApplicationService_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplicationService_Start_Call) RunAndReturn(run func() error) *MockApplicationService_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockApplicationService
func (_mock *MockApplicationService) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplicationService_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockApplicationService_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockApplicationService_Expecter) Stop() *MockApplicationService_Stop_Call {
	return &MockApplicationService_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockApplicationService_Stop_Call) Run(run func()) *MockApplicationService_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockApplicationService_Stop_Call) Return(err error) *MockApplicationService_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplicationService_Stop_Call) RunAndReturn(run func() error) *MockApplicationService_Stop_Call {
	_c.Call.Return(run)
	return _c
}
