---
openapi: 3.0.3
# https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#info-object
info:
    title: Sample internal API
    description: |
      Example of API design first approach and using golang stack applying
      clean-architecture and using viper, echo, gorm libraries.
    version: "1.0"
servers:
    - description: Use for Development
      url: /internal
paths:
components:
tags:
