// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package echo

import (
	"github.com/avisiedo/go-microservice-1/internal/api/http/public"
	"github.com/avisiedo/go-microservice-1/internal/domain/model"
	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHealthcheck creates a new instance of MockHealthcheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthcheck(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockHealthcheck {
	mock := &MockHealthcheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHealthcheck is an autogenerated mock type for the Healthcheck type
type MockHealthcheck struct {
	mock.Mock
}

type MockHealthcheck_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthcheck) EXPECT() *MockHealthcheck_Expecter {
	return &MockHealthcheck_Expecter{mock: &_m.Mock}
}

// GetLivez provides a mock function for the type MockHealthcheck
func (_mock *MockHealthcheck) GetLivez(ctx echo.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLivez")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHealthcheck_GetLivez_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLivez'
type MockHealthcheck_GetLivez_Call struct {
	*mock.Call
}

// GetLivez is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *MockHealthcheck_Expecter) GetLivez(ctx interface{}) *MockHealthcheck_GetLivez_Call {
	return &MockHealthcheck_GetLivez_Call{Call: _e.mock.On("GetLivez", ctx)}
}

func (_c *MockHealthcheck_GetLivez_Call) Run(run func(ctx echo.Context)) *MockHealthcheck_GetLivez_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHealthcheck_GetLivez_Call) Return(err error) *MockHealthcheck_GetLivez_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHealthcheck_GetLivez_Call) RunAndReturn(run func(ctx echo.Context) error) *MockHealthcheck_GetLivez_Call {
	_c.Call.Return(run)
	return _c
}

// GetReadyz provides a mock function for the type MockHealthcheck
func (_mock *MockHealthcheck) GetReadyz(ctx echo.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetReadyz")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHealthcheck_GetReadyz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReadyz'
type MockHealthcheck_GetReadyz_Call struct {
	*mock.Call
}

// GetReadyz is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *MockHealthcheck_Expecter) GetReadyz(ctx interface{}) *MockHealthcheck_GetReadyz_Call {
	return &MockHealthcheck_GetReadyz_Call{Call: _e.mock.On("GetReadyz", ctx)}
}

func (_c *MockHealthcheck_GetReadyz_Call) Run(run func(ctx echo.Context)) *MockHealthcheck_GetReadyz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHealthcheck_GetReadyz_Call) Return(err error) *MockHealthcheck_GetReadyz_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHealthcheck_GetReadyz_Call) RunAndReturn(run func(ctx echo.Context) error) *MockHealthcheck_GetReadyz_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInstrumentation creates a new instance of MockInstrumentation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstrumentation(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockInstrumentation {
	mock := &MockInstrumentation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInstrumentation is an autogenerated mock type for the Instrumentation type
type MockInstrumentation struct {
	mock.Mock
}

type MockInstrumentation_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstrumentation) EXPECT() *MockInstrumentation_Expecter {
	return &MockInstrumentation_Expecter{mock: &_m.Mock}
}

// GetMetrics provides a mock function for the type MockInstrumentation
func (_mock *MockInstrumentation) GetMetrics(ctx echo.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMetrics")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInstrumentation_GetMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetrics'
type MockInstrumentation_GetMetrics_Call struct {
	*mock.Call
}

// GetMetrics is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *MockInstrumentation_Expecter) GetMetrics(ctx interface{}) *MockInstrumentation_GetMetrics_Call {
	return &MockInstrumentation_GetMetrics_Call{Call: _e.mock.On("GetMetrics", ctx)}
}

func (_c *MockInstrumentation_GetMetrics_Call) Run(run func(ctx echo.Context)) *MockInstrumentation_GetMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInstrumentation_GetMetrics_Call) Return(err error) *MockInstrumentation_GetMetrics_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInstrumentation_GetMetrics_Call) RunAndReturn(run func(ctx echo.Context) error) *MockInstrumentation_GetMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOpenAPI creates a new instance of MockOpenAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOpenAPI(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockOpenAPI {
	mock := &MockOpenAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOpenAPI is an autogenerated mock type for the OpenAPI type
type MockOpenAPI struct {
	mock.Mock
}

type MockOpenAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOpenAPI) EXPECT() *MockOpenAPI_Expecter {
	return &MockOpenAPI_Expecter{mock: &_m.Mock}
}

// GetOpenapi provides a mock function for the type MockOpenAPI
func (_mock *MockOpenAPI) GetOpenapi(ctx echo.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOpenapi")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOpenAPI_GetOpenapi_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOpenapi'
type MockOpenAPI_GetOpenapi_Call struct {
	*mock.Call
}

// GetOpenapi is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *MockOpenAPI_Expecter) GetOpenapi(ctx interface{}) *MockOpenAPI_GetOpenapi_Call {
	return &MockOpenAPI_GetOpenapi_Call{Call: _e.mock.On("GetOpenapi", ctx)}
}

func (_c *MockOpenAPI_GetOpenapi_Call) Run(run func(ctx echo.Context)) *MockOpenAPI_GetOpenapi_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOpenAPI_GetOpenapi_Call) Return(err error) *MockOpenAPI_GetOpenapi_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOpenAPI_GetOpenapi_Call) RunAndReturn(run func(ctx echo.Context) error) *MockOpenAPI_GetOpenapi_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPrivate creates a new instance of MockPrivate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrivate(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockPrivate {
	mock := &MockPrivate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPrivate is an autogenerated mock type for the Private type
type MockPrivate struct {
	mock.Mock
}

type MockPrivate_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrivate) EXPECT() *MockPrivate_Expecter {
	return &MockPrivate_Expecter{mock: &_m.Mock}
}

// NewMockTodo creates a new instance of MockTodo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodo(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockTodo {
	mock := &MockTodo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTodo is an autogenerated mock type for the Todo type
type MockTodo struct {
	mock.Mock
}

type MockTodo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodo) EXPECT() *MockTodo_Expecter {
	return &MockTodo_Expecter{mock: &_m.Mock}
}

// CreateTodo provides a mock function for the type MockTodo
func (_mock *MockTodo) CreateTodo(ctx echo.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodo_CreateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTodo'
type MockTodo_CreateTodo_Call struct {
	*mock.Call
}

// CreateTodo is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *MockTodo_Expecter) CreateTodo(ctx interface{}) *MockTodo_CreateTodo_Call {
	return &MockTodo_CreateTodo_Call{Call: _e.mock.On("CreateTodo", ctx)}
}

func (_c *MockTodo_CreateTodo_Call) Run(run func(ctx echo.Context)) *MockTodo_CreateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodo_CreateTodo_Call) Return(err error) *MockTodo_CreateTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodo_CreateTodo_Call) RunAndReturn(run func(ctx echo.Context) error) *MockTodo_CreateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTodo provides a mock function for the type MockTodo
func (_mock *MockTodo) DeleteTodo(ctx echo.Context, todoId types.UUID) error {
	ret := _mock.Called(ctx, todoId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context, types.UUID) error); ok {
		r0 = returnFunc(ctx, todoId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodo_DeleteTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTodo'
type MockTodo_DeleteTodo_Call struct {
	*mock.Call
}

// DeleteTodo is a helper method to define mock.On call
//   - ctx echo.Context
//   - todoId types.UUID
func (_e *MockTodo_Expecter) DeleteTodo(ctx interface{}, todoId interface{}) *MockTodo_DeleteTodo_Call {
	return &MockTodo_DeleteTodo_Call{Call: _e.mock.On("DeleteTodo", ctx, todoId)}
}

func (_c *MockTodo_DeleteTodo_Call) Run(run func(ctx echo.Context, todoId types.UUID)) *MockTodo_DeleteTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		var arg1 types.UUID
		if args[1] != nil {
			arg1 = args[1].(types.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodo_DeleteTodo_Call) Return(err error) *MockTodo_DeleteTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodo_DeleteTodo_Call) RunAndReturn(run func(ctx echo.Context, todoId types.UUID) error) *MockTodo_DeleteTodo_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTodos provides a mock function for the type MockTodo
func (_mock *MockTodo) GetAllTodos(ctx echo.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTodos")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodo_GetAllTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTodos'
type MockTodo_GetAllTodos_Call struct {
	*mock.Call
}

// GetAllTodos is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *MockTodo_Expecter) GetAllTodos(ctx interface{}) *MockTodo_GetAllTodos_Call {
	return &MockTodo_GetAllTodos_Call{Call: _e.mock.On("GetAllTodos", ctx)}
}

func (_c *MockTodo_GetAllTodos_Call) Run(run func(ctx echo.Context)) *MockTodo_GetAllTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodo_GetAllTodos_Call) Return(err error) *MockTodo_GetAllTodos_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodo_GetAllTodos_Call) RunAndReturn(run func(ctx echo.Context) error) *MockTodo_GetAllTodos_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodo provides a mock function for the type MockTodo
func (_mock *MockTodo) GetTodo(ctx echo.Context, todoId types.UUID) error {
	ret := _mock.Called(ctx, todoId)

	if len(ret) == 0 {
		panic("no return value specified for GetTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context, types.UUID) error); ok {
		r0 = returnFunc(ctx, todoId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodo_GetTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodo'
type MockTodo_GetTodo_Call struct {
	*mock.Call
}

// GetTodo is a helper method to define mock.On call
//   - ctx echo.Context
//   - todoId types.UUID
func (_e *MockTodo_Expecter) GetTodo(ctx interface{}, todoId interface{}) *MockTodo_GetTodo_Call {
	return &MockTodo_GetTodo_Call{Call: _e.mock.On("GetTodo", ctx, todoId)}
}

func (_c *MockTodo_GetTodo_Call) Run(run func(ctx echo.Context, todoId types.UUID)) *MockTodo_GetTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		var arg1 types.UUID
		if args[1] != nil {
			arg1 = args[1].(types.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodo_GetTodo_Call) Return(err error) *MockTodo_GetTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodo_GetTodo_Call) RunAndReturn(run func(ctx echo.Context, todoId types.UUID) error) *MockTodo_GetTodo_Call {
	_c.Call.Return(run)
	return _c
}

// PatchTodo provides a mock function for the type MockTodo
func (_mock *MockTodo) PatchTodo(ctx echo.Context, todoId types.UUID) error {
	ret := _mock.Called(ctx, todoId)

	if len(ret) == 0 {
		panic("no return value specified for PatchTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context, types.UUID) error); ok {
		r0 = returnFunc(ctx, todoId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodo_PatchTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchTodo'
type MockTodo_PatchTodo_Call struct {
	*mock.Call
}

// PatchTodo is a helper method to define mock.On call
//   - ctx echo.Context
//   - todoId types.UUID
func (_e *MockTodo_Expecter) PatchTodo(ctx interface{}, todoId interface{}) *MockTodo_PatchTodo_Call {
	return &MockTodo_PatchTodo_Call{Call: _e.mock.On("PatchTodo", ctx, todoId)}
}

func (_c *MockTodo_PatchTodo_Call) Run(run func(ctx echo.Context, todoId types.UUID)) *MockTodo_PatchTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		var arg1 types.UUID
		if args[1] != nil {
			arg1 = args[1].(types.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodo_PatchTodo_Call) Return(err error) *MockTodo_PatchTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodo_PatchTodo_Call) RunAndReturn(run func(ctx echo.Context, todoId types.UUID) error) *MockTodo_PatchTodo_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTodo provides a mock function for the type MockTodo
func (_mock *MockTodo) UpdateTodo(ctx echo.Context, todoId types.UUID) error {
	ret := _mock.Called(ctx, todoId)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context, types.UUID) error); ok {
		r0 = returnFunc(ctx, todoId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodo_UpdateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTodo'
type MockTodo_UpdateTodo_Call struct {
	*mock.Call
}

// UpdateTodo is a helper method to define mock.On call
//   - ctx echo.Context
//   - todoId types.UUID
func (_e *MockTodo_Expecter) UpdateTodo(ctx interface{}, todoId interface{}) *MockTodo_UpdateTodo_Call {
	return &MockTodo_UpdateTodo_Call{Call: _e.mock.On("UpdateTodo", ctx, todoId)}
}

func (_c *MockTodo_UpdateTodo_Call) Run(run func(ctx echo.Context, todoId types.UUID)) *MockTodo_UpdateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		var arg1 types.UUID
		if args[1] != nil {
			arg1 = args[1].(types.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodo_UpdateTodo_Call) Return(err error) *MockTodo_UpdateTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodo_UpdateTodo_Call) RunAndReturn(run func(ctx echo.Context, todoId types.UUID) error) *MockTodo_UpdateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTodoInput creates a new instance of MockTodoInput. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoInput(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockTodoInput {
	mock := &MockTodoInput{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTodoInput is an autogenerated mock type for the TodoInput type
type MockTodoInput struct {
	mock.Mock
}

type MockTodoInput_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoInput) EXPECT() *MockTodoInput_Expecter {
	return &MockTodoInput_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTodoInput
func (_mock *MockTodoInput) Create(ctx echo.Context) (*model.Todo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) (*model.Todo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(echo.Context) *model.Todo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(echo.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoInput_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTodoInput_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *MockTodoInput_Expecter) Create(ctx interface{}) *MockTodoInput_Create_Call {
	return &MockTodoInput_Create_Call{Call: _e.mock.On("Create", ctx)}
}

func (_c *MockTodoInput_Create_Call) Run(run func(ctx echo.Context)) *MockTodoInput_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoInput_Create_Call) Return(todo *model.Todo, err error) *MockTodoInput_Create_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *MockTodoInput_Create_Call) RunAndReturn(run func(ctx echo.Context) (*model.Todo, error)) *MockTodoInput_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockTodoInput
func (_mock *MockTodoInput) GetAll(ctx echo.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoInput_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTodoInput_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *MockTodoInput_Expecter) GetAll(ctx interface{}) *MockTodoInput_GetAll_Call {
	return &MockTodoInput_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockTodoInput_GetAll_Call) Run(run func(ctx echo.Context)) *MockTodoInput_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoInput_GetAll_Call) Return(err error) *MockTodoInput_GetAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoInput_GetAll_Call) RunAndReturn(run func(ctx echo.Context) error) *MockTodoInput_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTodoOutput creates a new instance of MockTodoOutput. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoOutput(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockTodoOutput {
	mock := &MockTodoOutput{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTodoOutput is an autogenerated mock type for the TodoOutput type
type MockTodoOutput struct {
	mock.Mock
}

type MockTodoOutput_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoOutput) EXPECT() *MockTodoOutput_Expecter {
	return &MockTodoOutput_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTodoOutput
func (_mock *MockTodoOutput) Create(ctx echo.Context, data *model.Todo) (*public.ToDo, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *public.ToDo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context, *model.Todo) (*public.ToDo, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(echo.Context, *model.Todo) *public.ToDo); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*public.ToDo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(echo.Context, *model.Todo) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoOutput_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTodoOutput_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx echo.Context
//   - data *model.Todo
func (_e *MockTodoOutput_Expecter) Create(ctx interface{}, data interface{}) *MockTodoOutput_Create_Call {
	return &MockTodoOutput_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *MockTodoOutput_Create_Call) Run(run func(ctx echo.Context, data *model.Todo)) *MockTodoOutput_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		var arg1 *model.Todo
		if args[1] != nil {
			arg1 = args[1].(*model.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoOutput_Create_Call) Return(toDo *public.ToDo, err error) *MockTodoOutput_Create_Call {
	_c.Call.Return(toDo, err)
	return _c
}

func (_c *MockTodoOutput_Create_Call) RunAndReturn(run func(ctx echo.Context, data *model.Todo) (*public.ToDo, error)) *MockTodoOutput_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockTodoOutput
func (_mock *MockTodoOutput) Get(ctx echo.Context, data *model.Todo) (*public.ToDo, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *public.ToDo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context, *model.Todo) (*public.ToDo, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(echo.Context, *model.Todo) *public.ToDo); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*public.ToDo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(echo.Context, *model.Todo) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoOutput_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTodoOutput_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx echo.Context
//   - data *model.Todo
func (_e *MockTodoOutput_Expecter) Get(ctx interface{}, data interface{}) *MockTodoOutput_Get_Call {
	return &MockTodoOutput_Get_Call{Call: _e.mock.On("Get", ctx, data)}
}

func (_c *MockTodoOutput_Get_Call) Run(run func(ctx echo.Context, data *model.Todo)) *MockTodoOutput_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		var arg1 *model.Todo
		if args[1] != nil {
			arg1 = args[1].(*model.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoOutput_Get_Call) Return(toDo *public.ToDo, err error) *MockTodoOutput_Get_Call {
	_c.Call.Return(toDo, err)
	return _c
}

func (_c *MockTodoOutput_Get_Call) RunAndReturn(run func(ctx echo.Context, data *model.Todo) (*public.ToDo, error)) *MockTodoOutput_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockTodoOutput
func (_mock *MockTodoOutput) GetAll(ctx echo.Context, data []model.Todo) ([]public.ToDo, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []public.ToDo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context, []model.Todo) ([]public.ToDo, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(echo.Context, []model.Todo) []public.ToDo); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]public.ToDo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(echo.Context, []model.Todo) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoOutput_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTodoOutput_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx echo.Context
//   - data []model.Todo
func (_e *MockTodoOutput_Expecter) GetAll(ctx interface{}, data interface{}) *MockTodoOutput_GetAll_Call {
	return &MockTodoOutput_GetAll_Call{Call: _e.mock.On("GetAll", ctx, data)}
}

func (_c *MockTodoOutput_GetAll_Call) Run(run func(ctx echo.Context, data []model.Todo)) *MockTodoOutput_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		var arg1 []model.Todo
		if args[1] != nil {
			arg1 = args[1].([]model.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoOutput_GetAll_Call) Return(toDos []public.ToDo, err error) *MockTodoOutput_GetAll_Call {
	_c.Call.Return(toDos, err)
	return _c
}

func (_c *MockTodoOutput_GetAll_Call) RunAndReturn(run func(ctx echo.Context, data []model.Todo) ([]public.ToDo, error)) *MockTodoOutput_GetAll_Call {
	_c.Call.Return(run)
	return _c
}
