// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package db

import (
	"context"

	"github.com/avisiedo/go-microservice-1/internal/domain/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTodoRepository creates a new instance of MockTodoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTodoRepository {
	mock := &MockTodoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTodoRepository is an autogenerated mock type for the TodoRepository type
type MockTodoRepository struct {
	mock.Mock
}

type MockTodoRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoRepository) EXPECT() *MockTodoRepository_Expecter {
	return &MockTodoRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTodoRepository
func (_mock *MockTodoRepository) Create(ctx context.Context, todo *model.Todo) (*model.Todo, error) {
	ret := _mock.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Todo) (*model.Todo, error)); ok {
		return returnFunc(ctx, todo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Todo) *model.Todo); ok {
		r0 = returnFunc(ctx, todo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Todo) error); ok {
		r1 = returnFunc(ctx, todo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTodoRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - todo *model.Todo
func (_e *MockTodoRepository_Expecter) Create(ctx interface{}, todo interface{}) *MockTodoRepository_Create_Call {
	return &MockTodoRepository_Create_Call{Call: _e.mock.On("Create", ctx, todo)}
}

func (_c *MockTodoRepository_Create_Call) Run(run func(ctx context.Context, todo *model.Todo)) *MockTodoRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Todo
		if args[1] != nil {
			arg1 = args[1].(*model.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoRepository_Create_Call) Return(todo1 *model.Todo, err error) *MockTodoRepository_Create_Call {
	_c.Call.Return(todo1, err)
	return _c
}

func (_c *MockTodoRepository_Create_Call) RunAndReturn(run func(ctx context.Context, todo *model.Todo) (*model.Todo, error)) *MockTodoRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUUID provides a mock function for the type MockTodoRepository
func (_mock *MockTodoRepository) DeleteByUUID(ctx context.Context, uuid1 uuid.UUID) error {
	ret := _mock.Called(ctx, uuid1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUUID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, uuid1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoRepository_DeleteByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUUID'
type MockTodoRepository_DeleteByUUID_Call struct {
	*mock.Call
}

// DeleteByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid1 uuid.UUID
func (_e *MockTodoRepository_Expecter) DeleteByUUID(ctx interface{}, uuid1 interface{}) *MockTodoRepository_DeleteByUUID_Call {
	return &MockTodoRepository_DeleteByUUID_Call{Call: _e.mock.On("DeleteByUUID", ctx, uuid1)}
}

func (_c *MockTodoRepository_DeleteByUUID_Call) Run(run func(ctx context.Context, uuid1 uuid.UUID)) *MockTodoRepository_DeleteByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoRepository_DeleteByUUID_Call) Return(err error) *MockTodoRepository_DeleteByUUID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoRepository_DeleteByUUID_Call) RunAndReturn(run func(ctx context.Context, uuid1 uuid.UUID) error) *MockTodoRepository_DeleteByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockTodoRepository
func (_mock *MockTodoRepository) GetAll(ctx context.Context) ([]model.Todo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Todo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Todo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTodoRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTodoRepository_Expecter) GetAll(ctx interface{}) *MockTodoRepository_GetAll_Call {
	return &MockTodoRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockTodoRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockTodoRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoRepository_GetAll_Call) Return(todos []model.Todo, err error) *MockTodoRepository_GetAll_Call {
	_c.Call.Return(todos, err)
	return _c
}

func (_c *MockTodoRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]model.Todo, error)) *MockTodoRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUUID provides a mock function for the type MockTodoRepository
func (_mock *MockTodoRepository) GetByUUID(ctx context.Context, uuid1 uuid.UUID) (*model.Todo, error) {
	ret := _mock.Called(ctx, uuid1)

	if len(ret) == 0 {
		panic("no return value specified for GetByUUID")
	}

	var r0 *model.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Todo, error)); ok {
		return returnFunc(ctx, uuid1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Todo); ok {
		r0 = returnFunc(ctx, uuid1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, uuid1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoRepository_GetByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUUID'
type MockTodoRepository_GetByUUID_Call struct {
	*mock.Call
}

// GetByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid1 uuid.UUID
func (_e *MockTodoRepository_Expecter) GetByUUID(ctx interface{}, uuid1 interface{}) *MockTodoRepository_GetByUUID_Call {
	return &MockTodoRepository_GetByUUID_Call{Call: _e.mock.On("GetByUUID", ctx, uuid1)}
}

func (_c *MockTodoRepository_GetByUUID_Call) Run(run func(ctx context.Context, uuid1 uuid.UUID)) *MockTodoRepository_GetByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoRepository_GetByUUID_Call) Return(todo *model.Todo, err error) *MockTodoRepository_GetByUUID_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *MockTodoRepository_GetByUUID_Call) RunAndReturn(run func(ctx context.Context, uuid1 uuid.UUID) (*model.Todo, error)) *MockTodoRepository_GetByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTodoRepository
func (_mock *MockTodoRepository) Update(ctx context.Context, todo *model.Todo) (*model.Todo, error) {
	ret := _mock.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Todo) (*model.Todo, error)); ok {
		return returnFunc(ctx, todo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Todo) *model.Todo); ok {
		r0 = returnFunc(ctx, todo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Todo) error); ok {
		r1 = returnFunc(ctx, todo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTodoRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - todo *model.Todo
func (_e *MockTodoRepository_Expecter) Update(ctx interface{}, todo interface{}) *MockTodoRepository_Update_Call {
	return &MockTodoRepository_Update_Call{Call: _e.mock.On("Update", ctx, todo)}
}

func (_c *MockTodoRepository_Update_Call) Run(run func(ctx context.Context, todo *model.Todo)) *MockTodoRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Todo
		if args[1] != nil {
			arg1 = args[1].(*model.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoRepository_Update_Call) Return(todo1 *model.Todo, err error) *MockTodoRepository_Update_Call {
	_c.Call.Return(todo1, err)
	return _c
}

func (_c *MockTodoRepository_Update_Call) RunAndReturn(run func(ctx context.Context, todo *model.Todo) (*model.Todo, error)) *MockTodoRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
