// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockApplication creates a new instance of MockApplication. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApplication(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApplication {
	mock := &MockApplication{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockApplication is an autogenerated mock type for the Application type
type MockApplication struct {
	mock.Mock
}

type MockApplication_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApplication) EXPECT() *MockApplication_Expecter {
	return &MockApplication_Expecter{mock: &_m.Mock}
}

// CreateTodo provides a mock function for the type MockApplication
func (_mock *MockApplication) CreateTodo(ctx echo.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplication_CreateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTodo'
type MockApplication_CreateTodo_Call struct {
	*mock.Call
}

// CreateTodo is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *MockApplication_Expecter) CreateTodo(ctx interface{}) *MockApplication_CreateTodo_Call {
	return &MockApplication_CreateTodo_Call{Call: _e.mock.On("CreateTodo", ctx)}
}

func (_c *MockApplication_CreateTodo_Call) Run(run func(ctx echo.Context)) *MockApplication_CreateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockApplication_CreateTodo_Call) Return(err error) *MockApplication_CreateTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplication_CreateTodo_Call) RunAndReturn(run func(ctx echo.Context) error) *MockApplication_CreateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTodo provides a mock function for the type MockApplication
func (_mock *MockApplication) DeleteTodo(ctx echo.Context, todoId types.UUID) error {
	ret := _mock.Called(ctx, todoId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context, types.UUID) error); ok {
		r0 = returnFunc(ctx, todoId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplication_DeleteTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTodo'
type MockApplication_DeleteTodo_Call struct {
	*mock.Call
}

// DeleteTodo is a helper method to define mock.On call
//   - ctx echo.Context
//   - todoId types.UUID
func (_e *MockApplication_Expecter) DeleteTodo(ctx interface{}, todoId interface{}) *MockApplication_DeleteTodo_Call {
	return &MockApplication_DeleteTodo_Call{Call: _e.mock.On("DeleteTodo", ctx, todoId)}
}

func (_c *MockApplication_DeleteTodo_Call) Run(run func(ctx echo.Context, todoId types.UUID)) *MockApplication_DeleteTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		var arg1 types.UUID
		if args[1] != nil {
			arg1 = args[1].(types.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApplication_DeleteTodo_Call) Return(err error) *MockApplication_DeleteTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplication_DeleteTodo_Call) RunAndReturn(run func(ctx echo.Context, todoId types.UUID) error) *MockApplication_DeleteTodo_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTodos provides a mock function for the type MockApplication
func (_mock *MockApplication) GetAllTodos(ctx echo.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTodos")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplication_GetAllTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTodos'
type MockApplication_GetAllTodos_Call struct {
	*mock.Call
}

// GetAllTodos is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *MockApplication_Expecter) GetAllTodos(ctx interface{}) *MockApplication_GetAllTodos_Call {
	return &MockApplication_GetAllTodos_Call{Call: _e.mock.On("GetAllTodos", ctx)}
}

func (_c *MockApplication_GetAllTodos_Call) Run(run func(ctx echo.Context)) *MockApplication_GetAllTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockApplication_GetAllTodos_Call) Return(err error) *MockApplication_GetAllTodos_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplication_GetAllTodos_Call) RunAndReturn(run func(ctx echo.Context) error) *MockApplication_GetAllTodos_Call {
	_c.Call.Return(run)
	return _c
}

// GetLivez provides a mock function for the type MockApplication
func (_mock *MockApplication) GetLivez(ctx echo.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLivez")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplication_GetLivez_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLivez'
type MockApplication_GetLivez_Call struct {
	*mock.Call
}

// GetLivez is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *MockApplication_Expecter) GetLivez(ctx interface{}) *MockApplication_GetLivez_Call {
	return &MockApplication_GetLivez_Call{Call: _e.mock.On("GetLivez", ctx)}
}

func (_c *MockApplication_GetLivez_Call) Run(run func(ctx echo.Context)) *MockApplication_GetLivez_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockApplication_GetLivez_Call) Return(err error) *MockApplication_GetLivez_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplication_GetLivez_Call) RunAndReturn(run func(ctx echo.Context) error) *MockApplication_GetLivez_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetrics provides a mock function for the type MockApplication
func (_mock *MockApplication) GetMetrics(ctx echo.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMetrics")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplication_GetMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetrics'
type MockApplication_GetMetrics_Call struct {
	*mock.Call
}

// GetMetrics is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *MockApplication_Expecter) GetMetrics(ctx interface{}) *MockApplication_GetMetrics_Call {
	return &MockApplication_GetMetrics_Call{Call: _e.mock.On("GetMetrics", ctx)}
}

func (_c *MockApplication_GetMetrics_Call) Run(run func(ctx echo.Context)) *MockApplication_GetMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockApplication_GetMetrics_Call) Return(err error) *MockApplication_GetMetrics_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplication_GetMetrics_Call) RunAndReturn(run func(ctx echo.Context) error) *MockApplication_GetMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetOpenapi provides a mock function for the type MockApplication
func (_mock *MockApplication) GetOpenapi(ctx echo.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOpenapi")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplication_GetOpenapi_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOpenapi'
type MockApplication_GetOpenapi_Call struct {
	*mock.Call
}

// GetOpenapi is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *MockApplication_Expecter) GetOpenapi(ctx interface{}) *MockApplication_GetOpenapi_Call {
	return &MockApplication_GetOpenapi_Call{Call: _e.mock.On("GetOpenapi", ctx)}
}

func (_c *MockApplication_GetOpenapi_Call) Run(run func(ctx echo.Context)) *MockApplication_GetOpenapi_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockApplication_GetOpenapi_Call) Return(err error) *MockApplication_GetOpenapi_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplication_GetOpenapi_Call) RunAndReturn(run func(ctx echo.Context) error) *MockApplication_GetOpenapi_Call {
	_c.Call.Return(run)
	return _c
}

// GetReadyz provides a mock function for the type MockApplication
func (_mock *MockApplication) GetReadyz(ctx echo.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetReadyz")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplication_GetReadyz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReadyz'
type MockApplication_GetReadyz_Call struct {
	*mock.Call
}

// GetReadyz is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *MockApplication_Expecter) GetReadyz(ctx interface{}) *MockApplication_GetReadyz_Call {
	return &MockApplication_GetReadyz_Call{Call: _e.mock.On("GetReadyz", ctx)}
}

func (_c *MockApplication_GetReadyz_Call) Run(run func(ctx echo.Context)) *MockApplication_GetReadyz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockApplication_GetReadyz_Call) Return(err error) *MockApplication_GetReadyz_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplication_GetReadyz_Call) RunAndReturn(run func(ctx echo.Context) error) *MockApplication_GetReadyz_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodo provides a mock function for the type MockApplication
func (_mock *MockApplication) GetTodo(ctx echo.Context, todoId types.UUID) error {
	ret := _mock.Called(ctx, todoId)

	if len(ret) == 0 {
		panic("no return value specified for GetTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context, types.UUID) error); ok {
		r0 = returnFunc(ctx, todoId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplication_GetTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodo'
type MockApplication_GetTodo_Call struct {
	*mock.Call
}

// GetTodo is a helper method to define mock.On call
//   - ctx echo.Context
//   - todoId types.UUID
func (_e *MockApplication_Expecter) GetTodo(ctx interface{}, todoId interface{}) *MockApplication_GetTodo_Call {
	return &MockApplication_GetTodo_Call{Call: _e.mock.On("GetTodo", ctx, todoId)}
}

func (_c *MockApplication_GetTodo_Call) Run(run func(ctx echo.Context, todoId types.UUID)) *MockApplication_GetTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		var arg1 types.UUID
		if args[1] != nil {
			arg1 = args[1].(types.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApplication_GetTodo_Call) Return(err error) *MockApplication_GetTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplication_GetTodo_Call) RunAndReturn(run func(ctx echo.Context, todoId types.UUID) error) *MockApplication_GetTodo_Call {
	_c.Call.Return(run)
	return _c
}

// PatchTodo provides a mock function for the type MockApplication
func (_mock *MockApplication) PatchTodo(ctx echo.Context, todoId types.UUID) error {
	ret := _mock.Called(ctx, todoId)

	if len(ret) == 0 {
		panic("no return value specified for PatchTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context, types.UUID) error); ok {
		r0 = returnFunc(ctx, todoId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplication_PatchTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchTodo'
type MockApplication_PatchTodo_Call struct {
	*mock.Call
}

// PatchTodo is a helper method to define mock.On call
//   - ctx echo.Context
//   - todoId types.UUID
func (_e *MockApplication_Expecter) PatchTodo(ctx interface{}, todoId interface{}) *MockApplication_PatchTodo_Call {
	return &MockApplication_PatchTodo_Call{Call: _e.mock.On("PatchTodo", ctx, todoId)}
}

func (_c *MockApplication_PatchTodo_Call) Run(run func(ctx echo.Context, todoId types.UUID)) *MockApplication_PatchTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		var arg1 types.UUID
		if args[1] != nil {
			arg1 = args[1].(types.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApplication_PatchTodo_Call) Return(err error) *MockApplication_PatchTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplication_PatchTodo_Call) RunAndReturn(run func(ctx echo.Context, todoId types.UUID) error) *MockApplication_PatchTodo_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTodo provides a mock function for the type MockApplication
func (_mock *MockApplication) UpdateTodo(ctx echo.Context, todoId types.UUID) error {
	ret := _mock.Called(ctx, todoId)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context, types.UUID) error); ok {
		r0 = returnFunc(ctx, todoId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplication_UpdateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTodo'
type MockApplication_UpdateTodo_Call struct {
	*mock.Call
}

// UpdateTodo is a helper method to define mock.On call
//   - ctx echo.Context
//   - todoId types.UUID
func (_e *MockApplication_Expecter) UpdateTodo(ctx interface{}, todoId interface{}) *MockApplication_UpdateTodo_Call {
	return &MockApplication_UpdateTodo_Call{Call: _e.mock.On("UpdateTodo", ctx, todoId)}
}

func (_c *MockApplication_UpdateTodo_Call) Run(run func(ctx echo.Context, todoId types.UUID)) *MockApplication_UpdateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		var arg1 types.UUID
		if args[1] != nil {
			arg1 = args[1].(types.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApplication_UpdateTodo_Call) Return(err error) *MockApplication_UpdateTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplication_UpdateTodo_Call) RunAndReturn(run func(ctx echo.Context, todoId types.UUID) error) *MockApplication_UpdateTodo_Call {
	_c.Call.Return(run)
	return _c
}
