// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interactor

import (
	"context"

	"github.com/avisiedo/go-microservice-1/internal/domain/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHealthcheckInteractor creates a new instance of MockHealthcheckInteractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthcheckInteractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthcheckInteractor {
	mock := &MockHealthcheckInteractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHealthcheckInteractor is an autogenerated mock type for the HealthcheckInteractor type
type MockHealthcheckInteractor struct {
	mock.Mock
}

type MockHealthcheckInteractor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthcheckInteractor) EXPECT() *MockHealthcheckInteractor_Expecter {
	return &MockHealthcheckInteractor_Expecter{mock: &_m.Mock}
}

// IsLive provides a mock function for the type MockHealthcheckInteractor
func (_mock *MockHealthcheckInteractor) IsLive() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsLive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHealthcheckInteractor_IsLive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsLive'
type MockHealthcheckInteractor_IsLive_Call struct {
	*mock.Call
}

// IsLive is a helper method to define mock.On call
func (_e *MockHealthcheckInteractor_Expecter) IsLive() *MockHealthcheckInteractor_IsLive_Call {
	return &MockHealthcheckInteractor_IsLive_Call{Call: _e.mock.On("IsLive")}
}

func (_c *MockHealthcheckInteractor_IsLive_Call) Run(run func()) *MockHealthcheckInteractor_IsLive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthcheckInteractor_IsLive_Call) Return(err error) *MockHealthcheckInteractor_IsLive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHealthcheckInteractor_IsLive_Call) RunAndReturn(run func() error) *MockHealthcheckInteractor_IsLive_Call {
	_c.Call.Return(run)
	return _c
}

// IsReady provides a mock function for the type MockHealthcheckInteractor
func (_mock *MockHealthcheckInteractor) IsReady() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsReady")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHealthcheckInteractor_IsReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsReady'
type MockHealthcheckInteractor_IsReady_Call struct {
	*mock.Call
}

// IsReady is a helper method to define mock.On call
func (_e *MockHealthcheckInteractor_Expecter) IsReady() *MockHealthcheckInteractor_IsReady_Call {
	return &MockHealthcheckInteractor_IsReady_Call{Call: _e.mock.On("IsReady")}
}

func (_c *MockHealthcheckInteractor_IsReady_Call) Run(run func()) *MockHealthcheckInteractor_IsReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthcheckInteractor_IsReady_Call) Return(err error) *MockHealthcheckInteractor_IsReady_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHealthcheckInteractor_IsReady_Call) RunAndReturn(run func() error) *MockHealthcheckInteractor_IsReady_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPrivate creates a new instance of MockPrivate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrivate(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrivate {
	mock := &MockPrivate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPrivate is an autogenerated mock type for the Private type
type MockPrivate struct {
	mock.Mock
}

type MockPrivate_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrivate) EXPECT() *MockPrivate_Expecter {
	return &MockPrivate_Expecter{mock: &_m.Mock}
}

// NewMockTodo creates a new instance of MockTodo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTodo {
	mock := &MockTodo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTodo is an autogenerated mock type for the Todo type
type MockTodo struct {
	mock.Mock
}

type MockTodo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodo) EXPECT() *MockTodo_Expecter {
	return &MockTodo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTodo
func (_mock *MockTodo) Create(ctx context.Context, todo *model.Todo) (*model.Todo, error) {
	ret := _mock.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Todo) (*model.Todo, error)); ok {
		return returnFunc(ctx, todo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Todo) *model.Todo); ok {
		r0 = returnFunc(ctx, todo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Todo) error); ok {
		r1 = returnFunc(ctx, todo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTodo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - todo *model.Todo
func (_e *MockTodo_Expecter) Create(ctx interface{}, todo interface{}) *MockTodo_Create_Call {
	return &MockTodo_Create_Call{Call: _e.mock.On("Create", ctx, todo)}
}

func (_c *MockTodo_Create_Call) Run(run func(ctx context.Context, todo *model.Todo)) *MockTodo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Todo
		if args[1] != nil {
			arg1 = args[1].(*model.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodo_Create_Call) Return(todo1 *model.Todo, err error) *MockTodo_Create_Call {
	_c.Call.Return(todo1, err)
	return _c
}

func (_c *MockTodo_Create_Call) RunAndReturn(run func(ctx context.Context, todo *model.Todo) (*model.Todo, error)) *MockTodo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockTodo
func (_mock *MockTodo) GetAll(ctx context.Context) ([]model.Todo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Todo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Todo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodo_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTodo_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTodo_Expecter) GetAll(ctx interface{}) *MockTodo_GetAll_Call {
	return &MockTodo_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockTodo_GetAll_Call) Run(run func(ctx context.Context)) *MockTodo_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodo_GetAll_Call) Return(todos []model.Todo, err error) *MockTodo_GetAll_Call {
	_c.Call.Return(todos, err)
	return _c
}

func (_c *MockTodo_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]model.Todo, error)) *MockTodo_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUUID provides a mock function for the type MockTodo
func (_mock *MockTodo) GetByUUID(ctx context.Context, uuid1 uuid.UUID) (*model.Todo, error) {
	ret := _mock.Called(ctx, uuid1)

	if len(ret) == 0 {
		panic("no return value specified for GetByUUID")
	}

	var r0 *model.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Todo, error)); ok {
		return returnFunc(ctx, uuid1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Todo); ok {
		r0 = returnFunc(ctx, uuid1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, uuid1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodo_GetByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUUID'
type MockTodo_GetByUUID_Call struct {
	*mock.Call
}

// GetByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid1 uuid.UUID
func (_e *MockTodo_Expecter) GetByUUID(ctx interface{}, uuid1 interface{}) *MockTodo_GetByUUID_Call {
	return &MockTodo_GetByUUID_Call{Call: _e.mock.On("GetByUUID", ctx, uuid1)}
}

func (_c *MockTodo_GetByUUID_Call) Run(run func(ctx context.Context, uuid1 uuid.UUID)) *MockTodo_GetByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodo_GetByUUID_Call) Return(todo *model.Todo, err error) *MockTodo_GetByUUID_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *MockTodo_GetByUUID_Call) RunAndReturn(run func(ctx context.Context, uuid1 uuid.UUID) (*model.Todo, error)) *MockTodo_GetByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function for the type MockTodo
func (_mock *MockTodo) Patch(ctx context.Context, todo *model.Todo) (*model.Todo, error) {
	ret := _mock.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *model.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Todo) (*model.Todo, error)); ok {
		return returnFunc(ctx, todo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Todo) *model.Todo); ok {
		r0 = returnFunc(ctx, todo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Todo) error); ok {
		r1 = returnFunc(ctx, todo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodo_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockTodo_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - todo *model.Todo
func (_e *MockTodo_Expecter) Patch(ctx interface{}, todo interface{}) *MockTodo_Patch_Call {
	return &MockTodo_Patch_Call{Call: _e.mock.On("Patch", ctx, todo)}
}

func (_c *MockTodo_Patch_Call) Run(run func(ctx context.Context, todo *model.Todo)) *MockTodo_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Todo
		if args[1] != nil {
			arg1 = args[1].(*model.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodo_Patch_Call) Return(todo1 *model.Todo, err error) *MockTodo_Patch_Call {
	_c.Call.Return(todo1, err)
	return _c
}

func (_c *MockTodo_Patch_Call) RunAndReturn(run func(ctx context.Context, todo *model.Todo) (*model.Todo, error)) *MockTodo_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTodo
func (_mock *MockTodo) Update(ctx context.Context, todo *model.Todo) (*model.Todo, error) {
	ret := _mock.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Todo) (*model.Todo, error)); ok {
		return returnFunc(ctx, todo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Todo) *model.Todo); ok {
		r0 = returnFunc(ctx, todo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Todo) error); ok {
		r1 = returnFunc(ctx, todo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTodo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - todo *model.Todo
func (_e *MockTodo_Expecter) Update(ctx interface{}, todo interface{}) *MockTodo_Update_Call {
	return &MockTodo_Update_Call{Call: _e.mock.On("Update", ctx, todo)}
}

func (_c *MockTodo_Update_Call) Run(run func(ctx context.Context, todo *model.Todo)) *MockTodo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Todo
		if args[1] != nil {
			arg1 = args[1].(*model.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodo_Update_Call) Return(todo1 *model.Todo, err error) *MockTodo_Update_Call {
	_c.Call.Return(todo1, err)
	return _c
}

func (_c *MockTodo_Update_Call) RunAndReturn(run func(ctx context.Context, todo *model.Todo) (*model.Todo, error)) *MockTodo_Update_Call {
	_c.Call.Return(run)
	return _c
}
